"""Auto migration

Revision ID: 9115f360cfe9
Revises: 
Create Date: 2021-07-29 16:52:54.526707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9115f360cfe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['web-management.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='web-management'
    )
    op.create_index(op.f('ix_web-management_user_role_user_name'), 'user_role', ['user_name'], unique=False, schema='web-management')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web-management_user_role_user_name'), table_name='user_role', schema='web-management')
    op.drop_table('user_role', schema='web-management')
    # ### end Alembic commands ###